# =====================================
# Color
#
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'popkirby/lightline-iceberg'
depends = ['lightline.vim', 'iceberg.vim']
hook_source = '''
source $XDG_CONFIG_HOME/dein/rc/color.rc.vim
'''

# =====================================
# Filer
#
[[plugins]]
repo = 'junegunn/fzf'
depends = 'fzf'
# [todo]:
hook_source = '''
source $XDG_CONFIG_HOME/dein/rc/fzf.rc.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo= 'Shougo/denite.nvim'
depends = 'neomru.vim'
on_cmd = 'Denite'
if = 'has("nvim")'
hook_post_source = '''
source $XDG_CONFIG_HOME/dein/rc/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_source = '''
source $XDG_CONFIG_HOME/dein/rc/vimfiler.rc.vim
'''

# =====================================
# Utility
#
[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'tsuyoshiwada/slack-memo-vim'
depends = 'mattn/webapi-vim'
hook_source = '''
source $XDG_CONFIG_HOME/dein/rc/slack-memo.rc.vim
'''

[[plugins]]
repo = 'mattn/gist-vim'
depends = 'mattn/webapi-vim'
hook_source = '''
source $XDG_CONFIG_HOME/dein/rc/gist-vim.rc.vim
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_source = '''
source $XDG_CONFIG_HOME/dein/rc/neoterm.rc.vim
'''

# =====================================
# Word Complete
#
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
source $XDG_CONFIG_HOME/dein/rc/deoplete.rc.vim
'''
